/*
 * knowledge.js — SELECTA's house-music brain food.
 *
 * A structured, fully-offline knowledge base covering:
 *   - GENRES      house subgenres: BPM ranges, origins, sound, key artists, essential tracks
 *   - ARTISTS     legends & modern selectors, with bios
 *   - LABELS      the imprints that built house music
 *   - TECHNIQUES  mixing craft: beatmatching, phrasing, EQ, harmonic mixing, transitions
 *   - CAMELOT     the full Camelot wheel + compatibility rules for harmonic mixing
 *   - GEAR        decks, mixers, software, monitoring
 *   - HISTORY     timeline from the Warehouse to today
 *   - TRACKS      a crate of classics with BPM / key / energy, used by the set builder
 *   - TIPS        booth wisdom, one at a time
 */

const DJ_KNOWLEDGE = {

  // ---- SUBGENRES -----------------------------------------------------------
  genres: [
    {
      id: 'chicago house',
      aliases: ['chicago', 'classic house', 'original house'],
      bpm: [118, 128],
      era: '1983–present',
      origin: 'Chicago, USA',
      sound: 'The blueprint. Four-on-the-floor drum machines (Roland TR-808/909), gospel-tinged vocals, jacking basslines and raw, stripped-down grooves born from disco edits at the Warehouse.',
      artists: ['Frankie Knuckles', 'Marshall Jefferson', 'Larry Heard', 'Jesse Saunders', 'Ron Hardy', 'Steve "Silk" Hurley'],
      essentials: ['Marshall Jefferson — Move Your Body (1986)', 'Frankie Knuckles — Your Love (1987)', 'Jesse Saunders — On and On (1984)', 'Steve "Silk" Hurley — Jack Your Body (1986)'],
    },
    {
      id: 'deep house',
      aliases: ['deep'],
      bpm: [118, 125],
      era: '1986–present',
      origin: 'Chicago → worldwide',
      sound: 'Warm, jazzy and soulful. Lush seventh chords, sub-heavy basslines, muted stabs, spacious pads and an unhurried groove. Larry Heard invented it; Kerri Chandler perfected the New Jersey strain.',
      artists: ['Larry Heard (Mr. Fingers)', 'Kerri Chandler', 'Moodymann', 'Theo Parrish', 'Dennis Ferrer', 'Kai Alcé'],
      essentials: ['Mr. Fingers — Can You Feel It (1986)', 'Kerri Chandler — Rain (1998)', 'Moodymann — Shades of Jae (1997)', 'Dennis Ferrer — Hey Hey (2010)'],
    },
    {
      id: 'acid house',
      aliases: ['acid'],
      bpm: [120, 130],
      era: '1987–present',
      origin: 'Chicago, USA',
      sound: 'Built on the squelching, resonant gurgle of the Roland TB-303 bass synthesizer. Hypnotic, psychedelic and relentless — it lit the fuse on the UK\'s Second Summer of Love in 1988.',
      artists: ['Phuture (DJ Pierre)', 'Armando', 'Adonis', 'Hardfloor', 'Josh Wink'],
      essentials: ['Phuture — Acid Tracks (1987)', 'Josh Wink — Higher State of Consciousness (1995)', 'Armando — Land of Confusion (1988)'],
    },
    {
      id: 'tech house',
      aliases: ['tech'],
      bpm: [124, 130],
      era: 'mid-1990s–present',
      origin: 'UK / worldwide',
      sound: 'House groove, techno toolkit. Rolling basslines, crisp percussion, minimal melodic content, maximum drive. Today\'s festival main-room staple via Hot Creations, Solid Grooves and Dirtybird.',
      artists: ['Jamie Jones', 'Green Velvet', 'Hot Since 82', 'Fisher', 'Chris Lake', 'Dom Dolla', 'Solardo', 'Michael Bibi'],
      essentials: ['Green Velvet & Patrick Topping — Voicemail (2016)', 'Fisher — Losing It (2018)', 'Hot Since 82 — Buggin\' (2019)', 'Dom Dolla — San Frandisco (2019)'],
    },
    {
      id: 'progressive house',
      aliases: ['progressive', 'prog house', 'prog'],
      bpm: [120, 128],
      era: '1990s–present',
      origin: 'UK',
      sound: 'Long, layered, journey-driven. Slow-burning builds, melodic tension and release over extended arrangements. Sasha & Digweed defined the DJ-as-storyteller era; Eric Prydz carries the torch.',
      artists: ['Sasha', 'John Digweed', 'Eric Prydz', 'Hernán Cattáneo', 'Guy J'],
      essentials: ['Eric Prydz — Opus (2015)', 'Sasha — Xpander (1999)', 'Leftfield — Song of Life (1992)'],
    },
    {
      id: 'french house',
      aliases: ['french touch', 'filter house', 'filter disco'],
      bpm: [115, 126],
      era: '1996–present',
      origin: 'Paris, France',
      sound: 'Filtered disco loops, sidechain pump, talkbox and glitter. Chopped 70s/80s samples run through phasers and low-pass filters — joyous, compressed, irresistible.',
      artists: ['Daft Punk', 'Cassius', 'Stardust', 'Alan Braxe', 'Fred Falke', 'Breakbot'],
      essentials: ['Stardust — Music Sounds Better With You (1998)', 'Daft Punk — Around the World (1997)', 'Cassius — 1999 (1999)', 'Alan Braxe & Fred Falke — Intro (2000)'],
    },
    {
      id: 'soulful house',
      aliases: ['soulful', 'vocal house', 'gospel house'],
      bpm: [120, 126],
      era: '1988–present',
      origin: 'New York / New Jersey, USA',
      sound: 'Full-throated vocals, live instrumentation, gospel and R&B DNA. The Body & Soul / Shelter sound — church for dancers. Masters at Work are the genre\'s master craftsmen.',
      artists: ['Masters at Work (Louie Vega & Kenny Dope)', 'David Morales', 'Todd Terry', 'Barbara Tucker', 'Dennis Ferrer', 'Michelle Weeks'],
      essentials: ['Barbara Tucker — Beautiful People (1994)', 'Masters at Work — Work (1993)', 'Ultra Naté — Free (1997)'],
    },
    {
      id: 'garage house',
      aliases: ['garage', 'new york house', 'ny house', 'paradise garage'],
      bpm: [118, 126],
      era: '1980s–present',
      origin: 'New York, USA',
      sound: 'Named for the Paradise Garage and Larry Levan. Gospel-soaked vocals, live-feeling grooves, disco lineage — smoother and songier than Chicago\'s raw jack tracks.',
      artists: ['Larry Levan', 'Tony Humphries', 'Blaze', 'Adeva'],
      essentials: ['Loleatta Holloway — Love Sensation (1980)', 'Blaze — Lovelee Dae (1997)'],
    },
    {
      id: 'uk garage',
      aliases: ['ukg', '2-step', 'speed garage'],
      bpm: [128, 135],
      era: '1994–present',
      origin: 'London, UK',
      sound: 'US garage pitched up and swung hard. Shuffled 2-step drums, time-stretched vocals, warping sub-bass. Todd Edwards\' chopped vocal micro-sampling is its holy grail.',
      artists: ['Todd Edwards', 'MJ Cole', 'Artful Dodger', 'DJ EZ', 'El-B'],
      essentials: ['Double 99 — Ripgroove (1997)', 'MJ Cole — Sincere (1998)', 'Artful Dodger — Re-Rewind (1999)'],
    },
    {
      id: 'afro house',
      aliases: ['afro', 'afro tech'],
      bpm: [110, 125],
      era: '2000s–present',
      origin: 'South Africa / worldwide',
      sound: 'Polyrhythmic percussion, organic textures, chants and deep hypnotic grooves. Black Coffee took it global; Keinemusik made it the sound of sunset sets everywhere.',
      artists: ['Black Coffee', 'Culoe De Song', 'Keinemusik (&ME, Rampa, Adam Port)', 'Themba', 'Enoo Napa'],
      essentials: ['Black Coffee — Superman (2010)', '&ME — The Rapture Pt.II (2018)', 'Culoe De Song — Webaba (2009)'],
    },
    {
      id: 'melodic house',
      aliases: ['melodic house & techno', 'melodic techno', 'melodic'],
      bpm: [118, 126],
      era: '2010s–present',
      origin: 'worldwide',
      sound: 'Emotive arps, cinematic pads, patient builds. The Anjunadeep / Afterlife axis — festival-scale feelings at a controlled tempo.',
      artists: ['Lane 8', 'Ben Böhmer', 'Tale of Us', 'Solomun', 'Âme', 'Dixon', 'Adriatique'],
      essentials: ['Âme — Rej (2005)', 'Ben Böhmer — Breathing (2019)', 'Solomun — Home (2009)'],
    },
    {
      id: 'organic house',
      aliases: ['organic', 'downtempo house', 'desert house'],
      bpm: [108, 120],
      era: '2010s–present',
      origin: 'worldwide',
      sound: 'Slow, earthy and textural — acoustic instruments, field recordings and hand percussion over deep electronic beds. The All Day I Dream sunrise-set sound.',
      artists: ['Lee Burridge', 'Sébastien Léger', 'YokoO', 'Bedouin'],
      essentials: ['Sébastien Léger — Lava (2019)', 'RÜFÜS DU SOL — Innerbloom (Lane 8 Remix) (2016)'],
    },
    {
      id: 'funky house',
      aliases: ['funky', 'disco house', 'jackin house', "jackin'"],
      bpm: [122, 128],
      era: '1990s–present',
      origin: 'Chicago / UK',
      sound: 'Chunky filtered disco and funk loops, big basslines, swing for days. The Chicago jackin\' school (Derrick Carter, DJ Sneak) meets UK Saturday-night energy.',
      artists: ['Derrick Carter', 'DJ Sneak', 'Mark Farina', 'Armand Van Helden', 'Purple Disco Machine'],
      essentials: ['Armand Van Helden — U Don\'t Know Me (1999)', 'DJ Sneak — You Can\'t Hide From Your Bud (1996)', 'Purple Disco Machine — Hypnotized (2020)'],
    },
    {
      id: 'bass house',
      aliases: ['g-house'],
      bpm: [124, 130],
      era: '2010s–present',
      origin: 'UK / USA',
      sound: 'House tempo, dubstep attitude. Growling mid-range basses, big drops, festival aggression. Night Bass and Confession run the scene.',
      artists: ['AC Slater', 'Jauz', 'Joyryde', 'Chris Lorenzo'],
      essentials: ['Chris Lorenzo — California Dreamin\' (2015)', 'Jauz — Feel the Volume (2015)'],
    },
    {
      id: 'lo-fi house',
      aliases: ['lofi house', 'lo-fi'],
      bpm: [118, 126],
      era: '2015–present',
      origin: 'internet / worldwide',
      sound: 'Deliberately dusty: tape saturation, crushed drums, hazy chords and VHS nostalgia. Born on YouTube channels, raised in basements.',
      artists: ['Mall Grab', 'DJ Boring', 'Ross From Friends', 'DJ Seinfeld'],
      essentials: ['DJ Boring — Winona (2016)', 'Ross From Friends — Talk To Me You\'ll Understand (2015)'],
    },
    {
      id: 'electro house',
      aliases: ['electro', 'fidget'],
      bpm: [125, 130],
      era: '2000s–2010s',
      origin: 'worldwide',
      sound: 'Distorted sawtooth basslines, big-room drops, blog-era swagger. The Ed Banger / mid-2000s festival sound that bridged house into EDM.',
      artists: ['Justice', 'Boys Noize', 'Deadmau5 (early)', 'Wolfgang Gartner'],
      essentials: ['Justice — D.A.N.C.E. (2007)', 'Deadmau5 — Ghosts \'n\' Stuff (2008)'],
    },
    {
      id: 'latin house',
      aliases: ['latin', 'tribal house', 'tribal'],
      bpm: [122, 130],
      era: '1990s–present',
      origin: 'New York / Miami / worldwide',
      sound: 'Congas, timbales, montuno pianos and relentless drum workouts. Danny Tenaglia\'s marathon tribal sets and today\'s Latin-club crossover wave.',
      artists: ['Danny Tenaglia', 'Erick Morillo', 'Hugel', 'The Martinez Brothers'],
      essentials: ['Danny Tenaglia — Music Is the Answer (1998)', 'Erick Morillo / Reel 2 Real — I Like to Move It (1994)'],
    },
  ],

  // ---- ARTISTS -------------------------------------------------------------
  artists: [
    { name: 'Frankie Knuckles', bio: 'The Godfather of House. Resident at Chicago\'s Warehouse (1977–82) — the club that gave house its name — where he blended disco, soul and drum machines into a new sound. Later a Grammy-winning remixer. Died 2014; a Chicago street bears his name.' },
    { name: 'Larry Levan', bio: 'Legendary resident of New York\'s Paradise Garage (1977–87). His marathon, emotionally-charged sets and obsessive sound-system tuning defined DJing as an art form. "Garage" music is literally named after his club.' },
    { name: 'Ron Hardy', bio: 'The wild man of Chicago\'s Music Box. Played louder, faster and rawer than anyone — reel-to-reel edits, tracks played through twice, total dancefloor frenzy. As foundational to house as Knuckles, twice as unhinged.' },
    { name: 'Larry Heard', bio: 'a.k.a. Mr. Fingers. Invented deep house with "Can You Feel It" and "Mystery of Love" (1985–86). A jazz drummer turned synth poet — the most sampled chords in house history.' },
    { name: 'Marshall Jefferson', bio: 'Wrote "Move Your Body (The House Music Anthem)" in 1986 — the first house track with piano, and the record that named the genre in its own lyrics.' },
    { name: 'Kerri Chandler', bio: 'The king of New Jersey deep house. Signature booming kick drums, church organs, and raw emotion. "Rain", "Atmosphere", the Kaoz Theory label — still headlining 30+ years in.' },
    { name: 'Masters at Work', bio: 'Louie Vega & Kenny "Dope" Gonzalez. New York\'s greatest production duo — soulful house, Latin jazz, thousands of remixes. Their Nuyorican Soul project brought live salsa and jazz into house.' },
    { name: 'Todd Terry', bio: 'Brooklyn sample-house pioneer. Hard, hip-hop-informed cut-ups ("Can You Party", "Bango"). His 1995 remix of Everything But The Girl\'s "Missing" is one of the biggest house records ever.' },
    { name: 'Danny Tenaglia', bio: 'New York\'s marathon man. 12-hour-plus tribal and progressive sets at Tunnel and Vinyl/Arc. A DJ\'s DJ, famous for total control of a room over an entire night.' },
    { name: 'Carl Cox', bio: 'The three-deck wizard. From UK acid-house raves to a 15-year Space Ibiza residency. Technically flawless, eternally joyful — "Oh yes, oh yes!"' },
    { name: 'Derrick Carter', bio: 'Chicago\'s jackin\' virtuoso. Impossibly funky, technically dazzling sets built on disco, boogie and raw Chicago tracks. Co-ran Classic Music Company with Luke Solomon.' },
    { name: 'Green Velvet', bio: 'Curtis Jones, also known as Cajmere. "Percolator" (1992) as Cajmere, "Flash" and "La La Land" as Green Velvet. Founded Cajual and Relief Records — Chicago house royalty who still tops festival bills.' },
    { name: 'Moodymann', bio: 'Kenny Dixon Jr. Detroit\'s enigmatic deep-house auteur — dusty soul samples, live-jam looseness, fierce independence. KDJ Records. Every crate digger\'s hero.' },
    { name: 'Theo Parrish', bio: 'Detroit-based sound sculptor. Slow-burning, texture-first DJ sets that stretch from jazz to raw house. Sound Signature label. Treats the mixer EQ as an instrument.' },
    { name: 'Black Coffee', bio: 'South African superstar who took Afro house global. Grammy winner, Hï Ibiza resident. Deep, percussive, spiritual — the most influential African electronic artist of his generation.' },
    { name: 'Honey Dijon', bio: 'Chicago-born, NYC-raised selector bridging classic house, disco and fashion-world glamour. Grammy-winning producer, Beyoncé collaborator, and a fierce keeper of house\'s Black and queer roots.' },
    { name: 'The Blessed Madonna', bio: 'Kentucky-born, Chicago-schooled DJ known for joyous, vinyl-deep sets spanning house, disco and rave. We Still Believe parties; remixed Dua Lipa\'s entire Club Future Nostalgia.' },
    { name: 'Peggy Gou', bio: 'Korean-born, Berlin-based DJ/producer. "It Makes You Forget" and "(It Goes Like) Nanana" made her one of the biggest house acts in the world. Gudu Records.' },
    { name: 'Jamie Jones', bio: 'Hot Creations boss and Paradise (DC-10 Ibiza) ringleader. Defined the mid-2010s deep/tech-house sound and the modern Ibiza party blueprint.' },
    { name: 'Sasha', bio: 'Welsh progressive-house pioneer. With John Digweed, defined the transatlantic superclub era (Renaissance, Twilo, Northern Exposure mixes). "Xpander" is the prog anthem.' },
    { name: 'Eric Prydz', bio: 'Swedish progressive titan. "Opus", "Pjanoo", "Call on Me"; the Pryda and Cirez D aliases; the HOLO show. Melody + patience + the biggest drops in prog.' },
    { name: 'Disclosure', bio: 'Lawrence brothers who rebooted UK garage and house for the streaming era. Settle (2013) — "Latch", "White Noise" — made house chart music again without dumbing it down.' },
    { name: 'DJ Pierre', bio: 'As one third of Phuture, discovered the TB-303 acid squelch that became "Acid Tracks" (1987) — accidentally inventing acid house while trying to program a bassline.' },
    { name: 'Louie Vega', bio: 'Half of Masters at Work, Nuyorican Soul mastermind, Grammy winner. Carries the torch of NY soulful house with weekly marathon sets and impeccable musicality.' },
    { name: 'Armand Van Helden', bio: 'Boston-raised NY house heavyweight. "U Don\'t Know Me", the genre-splitting "Professional Widow" remix, speed garage detours, and later Duck Sauce with A-Trak.' },
    { name: 'MK', bio: 'Marc Kinchen, Detroit-born remix king. His early-90s dub mixes (Nightcrawlers "Push the Feeling On") invented a chopped-vocal-organ-bass style so durable it re-conquered the charts 20 years later.' },
    { name: 'Todd Edwards', bio: 'New Jersey\'s "Todd the God". Micro-chopped vocal collage garage — the direct blueprint for UK garage and Daft Punk collaborator ("Face to Face", "Fragments of Time").' },
    { name: 'Solomun', bio: 'Diynamic label boss and Pacha Ibiza\'s marathon Sunday resident (+1 parties). Emotional, vocal-leaning melodic house with impeccable dramatic timing.' },
    { name: 'Fisher', bio: 'Australian ex-pro-surfer turned tech-house megastar. "Losing It" (2018) earned a Grammy nomination and soundtracked every festival on Earth. Maximum party, zero pretension.' },
    { name: 'Chris Lake', bio: 'British tech-house heavyweight, Black Book Records boss. "Turn Off the Lights" with Alesso, endless collabs with Fisher — the polished end of the modern tech-house machine.' },
    { name: 'Dom Dolla', bio: 'Melbourne tech-house hitmaker. "Take It", "San Frandisco", "Saving Up" — arena-filling grooves with pop instincts.' },
    { name: 'DJ Sneak', bio: 'Puerto Rico-born, Chicago-raised "house gangster". Filtered disco loops and chunky jackin\' grooves; a fierce guardian of house authenticity.' },
    { name: 'Mark Farina', bio: 'Chicago-born, San Francisco-adopted. Split between jackin\' house and his signature "Mushroom Jazz" downtempo series. Smooth as it gets.' },
    { name: 'Dennis Ferrer', bio: 'New York deep/soulful house craftsman, Objektivity boss. "Hey Hey" (2010) is the modern soulful anthem; also mentored the next NY generation.' },
    { name: 'Jesse Saunders', bio: 'Made "On and On" (1984), widely credited as the first house record ever pressed to vinyl — proof that Chicago kids could press their own future.' },
    { name: 'Paul Johnson', bio: 'Chicago jack legend behind "Get Get Down" (1999). Relentlessly funky, endlessly sampled. Passed in 2021 — his groove is immortal.' },
  ],

  // ---- LABELS ----------------------------------------------------------------
  labels: [
    { name: 'Trax Records', info: 'Chicago, 1984. THE house label — "Acid Tracks", "Can You Feel It", "Your Love". Notoriously pressed on recycled vinyl; the crackle is part of the mythology.' },
    { name: 'DJ International', info: 'Chicago, 1985. Trax\'s great rival — "Move Your Body", "Jack Your Body". Took house to the UK charts first.' },
    { name: 'Strictly Rhythm', info: 'New York, 1989. The 90s house factory: Armand Van Helden, Erick Morillo, Josh Wink, Ultra Naté. Thousands of releases, wall-to-wall classics.' },
    { name: 'Defected', info: 'UK, 1999. Today\'s biggest house institution — label, festival brand and Ibiza residency. Home to soulful, vocal and classic-leaning house; also runs Classic Music Company.' },
    { name: 'Nervous Records', info: 'New York, 1991. Louie Vega, Kerri Chandler, Mood II Swing, Byron Stingily — the iconic cartoon-head logo of NY house.' },
    { name: 'Cajual / Relief', info: 'Chicago, 1992. Green Velvet\'s twin labels: Cajual for the soul, Relief for the raw tracks. Derrick Carter, DJ Sneak, Paul Johnson all came through.' },
    { name: 'Nu Groove', info: 'New York, 1988–92. Short-lived but legendary — the Burrell brothers, early Kenny Dope, deep raw NY house that collectors still fight over.' },
    { name: 'Hot Creations', info: 'UK/Ibiza, 2010. Jamie Jones & Lee Foss. Defined the 2010s deep/tech-house wave and the Paradise party empire.' },
    { name: 'Dirtybird', info: 'San Francisco, 2005. Claude VonStroke\'s bass-heavy, humor-forward tech house. Booty bass meets BBQ.' },
    { name: 'Anjunadeep', info: 'UK, 2005. Above & Beyond\'s deep offshoot — Lane 8, Ben Böhmer, Yotto. The melodic/progressive standard-bearer.' },
    { name: 'Innervisions', info: 'Berlin, 2006. Dixon and Âme\'s home of emotive, arty deep house — "Rej" changed everything.' },
    { name: 'Keinemusik', info: 'Berlin, 2009. &ME, Rampa, Adam Port. The afro-tinged melodic sound of the 2020s, from Berlin backyards to global stadium sets.' },
    { name: 'Toolroom', info: 'UK, 2003. Mark Knight\'s tech-house powerhouse; also a major DJ education platform (Toolroom Academy).' },
    { name: 'Crosstown Rebels', info: 'UK, 2003. Damian Lazarus\'s home of leftfield, mystical house — Rebel Rave, Day Zero, Get Lost parties.' },
  ],

  // ---- MIXING TECHNIQUES -----------------------------------------------------
  techniques: [
    {
      id: 'beatmatching',
      aliases: ['beatmatch', 'beat matching', 'beat match', 'sync', 'tempo match', 'pitch fader'],
      name: 'Beatmatching',
      text: 'Matching the tempo and phase of two tracks so their kicks land together. Manual method: set the incoming track\'s pitch fader close, cue its downbeat "1", release on the playing track\'s "1", then correct drift — nudge the jog/platter to fix PHASE, move the pitch fader in small steps to fix TEMPO. If the incoming beat drifts ahead, it\'s too fast: pull pitch down slightly. Practice with two copies of the same track first. Sync buttons are fine, but manual beatmatching trains your ears to hear drift instantly — you\'ll need that the day sync lies to you.',
    },
    {
      id: 'phrasing',
      aliases: ['phrase', 'phrase mixing', 'bars', 'counting', 'structure'],
      name: 'Phrasing & song structure',
      text: 'House is built in 4-beat bars grouped into 8/16/32-bar phrases; sections (intro, breakdown, drop, outro) almost always change on phrase boundaries. Golden rule: start your incoming track on the FIRST beat of the playing track\'s phrase — usually where a new 16 or 32 begins (listen for a crash, a new element, or a fill in bar 16/32). Count "1-2-3-4, 2-2-3-4..." until it\'s automatic. If a blend feels wrong even though beats are locked, you\'re phrase-misaligned: the energy of the two songs is fighting. Mix intro-over-outro for the safest blends.',
    },
    {
      id: 'eq mixing',
      aliases: ['eq', 'equalizer', 'bass swap', 'eq swap', 'three band'],
      name: 'EQ mixing & the bass swap',
      text: 'Two basslines playing at full low-end turn a mix to mud — so only ONE track owns the bass at a time. The classic bass swap: bring the new track in with its LOW fully cut, blend mids/highs to taste, then at a phrase boundary swap the lows in one confident move (old track low down as new track low comes up — many DJs do it across a single bar). Also: carve mids slightly on the incoming track if two vocals or lead lines clash, and use highs to sneak percussion in early. Cut before you boost; boosting invites distortion.',
    },
    {
      id: 'harmonic mixing',
      aliases: ['harmonic', 'key mixing', 'mixed in key', 'camelot', 'key'],
      name: 'Harmonic mixing (Camelot wheel)',
      text: 'Mixing tracks in compatible musical keys so basslines, pads and vocals blend instead of clash. The Camelot wheel maps every key to a number (1–12) + letter (A=minor, B=major). Compatible moves from any key: SAME code (perfect), ±1 same letter (smooth, e.g. 8A→7A or 9A), same number other letter (relative major/minor, e.g. 8A→8B), and the +2 "energy boost" (e.g. 8A→10A) for a lift when the drums carry the transition. Ask me "what mixes with 8A?" and I\'ll do the math. Don\'t become a slave to it — key-clash matters most when melodic content overlaps; drum-heavy transitions forgive almost anything.',
    },
    {
      id: 'filter transitions',
      aliases: ['filter', 'filter sweep', 'high pass', 'low pass', 'hpf', 'lpf'],
      name: 'Filter transitions',
      text: 'The mixer\'s per-channel filter knob is the smoothest transition tool ever made. High-pass the OUTGOING track slowly (removes weight, creates space and tension) while the incoming track fills the bottom end, then release. A gentle low-pass on the incoming track lets you sneak it in dark and open it up dramatically. Keep resonance low for smooth blends; raise it for a dramatic squelchy sweep. Filters + one-bar bass swap = 90% of a modern house set.',
    },
    {
      id: 'looping',
      aliases: ['loop', 'loops', 'hot cue', 'hot cues', 'cue points'],
      name: 'Loops & hot cues',
      text: 'Loops extend a moment: capture a 4/8-bar loop of an outro to give yourself unlimited mixing runway, or loop a breakdown to build tension. Loop rolls (1/2, 1/4, 1/8 beat) create build-up stutters before a drop. Hot cues mark your landmarks — set them on the first beat, the breakdown, the drop, and the outro of every track in your library, and you can restructure a song live: skip a cheesy vocal, double a drop, jump straight to the good part. Preparation in the library is what makes it look effortless in the booth.',
    },
    {
      id: 'quick transitions',
      aliases: ['backspin', 'echo out', 'spinback', 'cut', 'drop mixing', 'tempo change', 'bpm jump'],
      name: 'Quick transitions & tempo jumps',
      text: 'Not every mix is a long blend. The ECHO OUT: hit the delay/echo FX on the outgoing track and cut its fader — the tail washes over while you slam the new track from a downbeat. The BACKSPIN: spin the platter backwards hard on beat 4 and drop the next track on the 1. The DEAD-STOP: kill everything for one silent beat, then drop — devastating at peak time, use once a night. These also solve big BPM jumps (e.g. 124 → 128): no beatmatching needed because the tracks never overlap. A breakdown with no drums is the other tempo-change cheat — ride the pitch fader while nothing rhythmic is playing.',
    },
    {
      id: 'gain staging',
      aliases: ['gain', 'levels', 'redlining', 'trim', 'volume', 'clipping'],
      name: 'Gain staging',
      text: 'Set each channel\'s TRIM so the loudest part of the track peaks around 0 dB (top of the green / first orange) on the channel meter — and match the two tracks by ear in the headphones before you blend. Never ride the master into the red: digital mixers clip harshly, the booth sounds worse not louder, and the sound engineer will hate you. If the room needs more volume, that\'s the house engineer\'s job, not your master fader. Consistent gain staging is the most audible difference between amateurs and pros.',
    },
    {
      id: 'set building',
      aliases: ['set', 'energy', 'warm up', 'warmup', 'peak time', 'closing', 'journey', 'reading the crowd', 'crowd'],
      name: 'Set building & reading the room',
      text: 'Think in an energy arc, not a playlist. WARM-UP (opening slot): deeper, lower BPM (118–123), no anthems — your job is to build atmosphere and leave the headliner room to go up. PEAK TIME: your biggest grooves and moments, 124–128+, but even here waves beat a flat ceiling — tension and release. CLOSING: take them down gracefully; end on emotion, not exhaustion. Read the room constantly: watch feet and hips, not phones. If a track is dying, mix out early — no track is worth losing the floor. And never play the headliner\'s known weapons before their set; warm-up etiquette is how you get rebooked.',
    },
    {
      id: 'vocal layering',
      aliases: ['acapella', 'a cappella', 'vocal', 'mashup', 'layering'],
      name: 'Acapella & tool layering',
      text: 'Laying a vocal (acapella) over an instrumental track is the classic house trick — instant "remix" the crowd has never heard. Rules: match or complement the KEY (harmonic mixing matters most here), align phrases so verse/chorus land on the instrumental\'s sections, and keep the vocal slightly below the beat in volume. Keep a folder of acapellas and DJ tools (drum loops, FX, risers) organized by BPM and key. Classic pairing: "Love Sensation" vocals over almost any 124 BPM pumper.',
    },
    {
      id: 'headphone cueing',
      aliases: ['cueing', 'headphones', 'cue', 'monitor', 'pfl', 'split cue'],
      name: 'Headphone cueing & monitoring',
      text: 'PFL/cue lets you hear the next track before the audience does. Classic single-ear technique: one cup on (cued track), one ear on the booth monitor (live mix), and beatmatch between them. Split-cue mode puts cue in one ear and master in the other electronically — great in loud booths. Keep headphone volume as low as workable; protect your ears, they\'re your entire career. And always check your blend in the MASTER cue before committing the crossfade.',
    },
    {
      id: 'library prep',
      aliases: ['library', 'crate', 'crate digging', 'organization', 'playlists', 'preparation', 'rekordbox prep'],
      name: 'Library prep & crate digging',
      text: 'Sets are won in the library, not the booth. Analyze everything for BPM and key; verify auto-detected beatgrids on anything with a live drummer or swing. Organize by energy and situation, not just genre — "openers", "groovers", "peak weapons", "emergency floor-fillers", "closers". Set hot cues on every track. Dig constantly: Bandcamp, Beatport, Traxsource (best for house), record stores, label back-catalogs, and the credits of tracks you love. The DJs who stand out play records the others haven\'t found yet.',
    },
  ],

  // ---- CAMELOT WHEEL ---------------------------------------------------------
  camelot: {
    // number: [minor (A), major (B)]
    1:  ['A-flat minor', 'B major'],
    2:  ['E-flat minor', 'F-sharp major'],
    3:  ['B-flat minor', 'D-flat major'],
    4:  ['F minor', 'A-flat major'],
    5:  ['C minor', 'E-flat major'],
    6:  ['G minor', 'B-flat major'],
    7:  ['D minor', 'F major'],
    8:  ['A minor', 'C major'],
    9:  ['E minor', 'G major'],
    10: ['B minor', 'D major'],
    11: ['F-sharp minor', 'A major'],
    12: ['D-flat minor', 'E major'],
  },

  // ---- GEAR ------------------------------------------------------------------
  gear: [
    { id: 'cdjs', aliases: ['cdj', 'players', 'decks', 'cdj-3000', 'xdj'], name: 'Media players (CDJs)', text: 'The Pioneer DJ (now AlphaTheta) CDJ is the club-standard media player — currently the CDJ-3000: 9-inch touchscreen, USB playback, hot cues, key sync/shift, beat jump. Rekordbox-analyzed USB sticks are the standard club workflow (always carry two, mirrored). Denon\'s SC6000 offers on-board streaming and dual layers but far fewer club installs. All-in-one units (XDJ-RX3/XZ, Denon Prime 4) bundle two decks + mixer — the best home/mobile middle ground.' },
    { id: 'turntables', aliases: ['turntable', 'vinyl', 'technics', '1200s', 'dvs', 'timecode'], name: 'Turntables & vinyl / DVS', text: 'The Technics SL-1200/1210 is the eternal standard — high-torque direct drive, pitch fader, basically indestructible. Vinyl demands real beatmatching (no waveforms, no sync) — the best ear training there is. DVS (Serato/Traktor/Rekordbox with timecode vinyl) gives you digital files with turntable feel. Care basics: quality cartridges (Ortofon Concorde, Shure legacy), correct tracking weight, and never leave records in the sun.' },
    { id: 'mixers', aliases: ['mixer', 'djm', 'rotary', 'isolator', 'xone'], name: 'Mixers', text: 'Club standard: Pioneer DJM-900NXS2 / DJM-A9 — 4 channels, 3-band EQ, per-channel filter, Sound Color and Beat FX. Allen & Heath Xone:92/96 is the analog-warmth choice with its legendary filters (Sasha, Villalobos camp). Rotary mixers (Bozak lineage, Rane MP2015, E&S DJR400, Alpha Recording System) swap faders for volume pots and often an isolator EQ — the deep-house purist\'s pick for long, musical blends. Learn on 3-band EQ + filter; everything else is flavor.' },
    { id: 'software', aliases: ['rekordbox', 'serato', 'traktor', 'controller', 'laptop', 'sync button'], name: 'Software & controllers', text: 'Rekordbox is the club-prep standard (its USB export is what CDJs read). Serato dominates open-format/scratch culture; Traktor is beloved for remix decks and stems; VirtualDJ and djay handle streaming-first workflows. Controllers (DDJ-FLX4/FLX10, Rane One) are the cheapest way to learn real skills — everything transfers to CDJs except the layout. Use sync as a tool, not a crutch: learn manual beatmatching first, then let sync free your hands for FX and EQ.' },
    { id: 'monitoring', aliases: ['monitors', 'booth', 'speakers', 'sound system', 'function one', 'earplugs'], name: 'Monitoring & sound systems', text: 'Booth monitors exist because the main system\'s sound reaches you late and smeared — mix off the booth, positioned at ear height. Legendary club systems: Richard Long\'s Paradise Garage rig, Funktion-One (Space Ibiza), Void, Danley, and the audiophile Klipschorn horns of Japanese listening bars. In the booth: musician\'s earplugs (flat -15 dB) on long nights — tinnitus is permanent and every veteran DJ will tell you the same thing.' },
    { id: 'headphones', aliases: ['headphone', 'hd-25', 'hd25'], name: 'Headphones', text: 'The Sennheiser HD-25 is the booth classic — loud, light, isolating, field-repairable part by part. Alternatives: Pioneer HDJ-X10, V-Moda Crossfade, AIAIAI TMA-2. You need isolation and punchy mids for beatmatching in a loud booth, not audiophile flatness. Closed-back always.' },
  ],

  // ---- HISTORY ---------------------------------------------------------------
  history: [
    { year: '1970s', event: 'Disco and NYC loft/party culture (David Mancuso\'s Loft, Nicky Siano\'s Gallery) establish the DJ as journey-builder and the dancefloor as sacred space.' },
    { year: '1977', event: 'The Paradise Garage opens in New York with Larry Levan as resident; the Warehouse opens in Chicago and brings Frankie Knuckles from NYC.' },
    { year: '1979', event: '"Disco Demolition Night" backlash pushes dance music underground — where Chicago kids rebuild it into something new.' },
    { year: '1983', event: 'Knuckles leaves the Warehouse for the Power Plant; Ron Hardy takes the Music Box into rawer territory. Record stores start labeling the sound "house" — as in "as played at the Warehouse".' },
    { year: '1984', event: 'Jesse Saunders presses "On and On" — widely called the first house record. Trax Records and DJ International launch.' },
    { year: '1986', event: 'Marshall Jefferson\'s "Move Your Body" adds piano and names the genre in its lyrics; Mr. Fingers\' "Can You Feel It" invents deep house. House hits the UK charts ("Jack Your Body" reaches #1 in January 1987).' },
    { year: '1987', event: 'Phuture\'s "Acid Tracks" unleashes the TB-303. Detroit techno emerges alongside from Atkins, May and Saunderson — house\'s sibling city sound.' },
    { year: '1988', event: 'The UK\'s "Second Summer of Love": acid house, warehouse parties and the birth of rave culture. Ibiza\'s Balearic scene (Alfredo at Amnesia) converts a generation of London DJs.' },
    { year: '1989–1994', event: 'New York\'s golden 90s: Strictly Rhythm, Nervous, Masters at Work, Todd Terry. New Jersey deep house via Kerri Chandler; UK progressive house via Sasha & Digweed; superclubs rise (Ministry of Sound 1991).' },
    { year: '1997–1999', event: 'The French Touch explosion — Daft Punk\'s Homework, Stardust, Cassius — filtered disco conquers the world. Speed garage and UK garage split off in London.' },
    { year: '2000s', event: 'Progressive and electro house dominate superclubs and festivals; digital DJing (Final Scratch → Serato, CDJs) transforms the booth; Berlin\'s minimal wave counters with restraint.' },
    { year: '2010s', event: 'EDM boom takes "house" to stadiums while deep and tech house (Hot Creations, Dirtybird, Defected revival) reclaim the underground. Disclosure and MK put real house back on the charts.' },
    { year: '2020s', event: 'Afro house and melodic house go global (Black Coffee, Keinemusik); Beyoncé\'s Renaissance and Drake\'s Honestly, Nevermind salute house\'s Black, queer roots; lo-fi and UKG revivals keep the cycle spinning.' },
  ],

  // ---- THE CRATE (for the set builder) ----------------------------------------
  // energy: 1 (deep opener) → 10 (peak-time weapon)
  tracks: [
    { artist: 'Mr. Fingers', title: 'Can You Feel It', year: 1986, bpm: 120, key: '5A', energy: 3, genre: 'deep house' },
    { artist: 'Larry Heard', title: 'The Sun Can\'t Compare', year: 2006, bpm: 122, key: '10A', energy: 4, genre: 'deep house' },
    { artist: 'Kerri Chandler', title: 'Rain', year: 1998, bpm: 124, key: '8A', energy: 5, genre: 'deep house' },
    { artist: 'Moodymann', title: 'Shades of Jae', year: 1997, bpm: 118, key: '4A', energy: 2, genre: 'deep house' },
    { artist: 'Pépé Bradock', title: 'Deep Burnt', year: 1999, bpm: 122, key: '6A', energy: 3, genre: 'deep house' },
    { artist: 'Frankie Knuckles', title: 'Your Love', year: 1987, bpm: 118, key: '9A', energy: 4, genre: 'chicago house' },
    { artist: 'Marshall Jefferson', title: 'Move Your Body', year: 1986, bpm: 122, key: '8B', energy: 6, genre: 'chicago house' },
    { artist: 'Phuture', title: 'Acid Tracks', year: 1987, bpm: 122, key: '8A', energy: 7, genre: 'acid house' },
    { artist: 'Green Velvet', title: 'Flash', year: 1995, bpm: 128, key: '9A', energy: 9, genre: 'tech house' },
    { artist: 'Cajmere ft. Dajae', title: 'Brighter Days (Underground Goodie Mix)', year: 1992, bpm: 124, key: '9A', energy: 6, genre: 'chicago house' },
    { artist: 'Paul Johnson', title: 'Get Get Down', year: 1999, bpm: 126, key: '11B', energy: 8, genre: 'funky house' },
    { artist: 'Armand Van Helden', title: 'U Don\'t Know Me', year: 1999, bpm: 126, key: '9A', energy: 8, genre: 'funky house' },
    { artist: 'Stardust', title: 'Music Sounds Better With You', year: 1998, bpm: 123, key: '11B', energy: 7, genre: 'french house' },
    { artist: 'Daft Punk', title: 'Around the World', year: 1997, bpm: 121, key: '11A', energy: 6, genre: 'french house' },
    { artist: 'Cassius', title: '1999', year: 1999, bpm: 123, key: '7B', energy: 6, genre: 'french house' },
    { artist: 'Barbara Tucker', title: 'Beautiful People', year: 1994, bpm: 124, key: '6A', energy: 6, genre: 'soulful house' },
    { artist: 'Ultra Naté', title: 'Free', year: 1997, bpm: 124, key: '12B', energy: 7, genre: 'soulful house' },
    { artist: 'Dennis Ferrer', title: 'Hey Hey', year: 2010, bpm: 122, key: '7A', energy: 6, genre: 'soulful house' },
    { artist: 'MK', title: 'Burning (Vibe Mix)', year: 1992, bpm: 124, key: '6A', energy: 6, genre: 'garage house' },
    { artist: 'Nightcrawlers', title: 'Push the Feeling On (MK Dub)', year: 1992, bpm: 124, key: '5A', energy: 7, genre: 'garage house' },
    { artist: 'Double 99', title: 'Ripgroove', year: 1997, bpm: 130, key: '6A', energy: 9, genre: 'uk garage' },
    { artist: 'Todd Edwards', title: 'Shut the Door', year: 1996, bpm: 126, key: '9B', energy: 7, genre: 'uk garage' },
    { artist: 'Âme', title: 'Rej', year: 2005, bpm: 122, key: '9A', energy: 5, genre: 'melodic house' },
    { artist: 'Solomun', title: 'Home', year: 2009, bpm: 121, key: '8A', energy: 4, genre: 'melodic house' },
    { artist: 'Ben Böhmer', title: 'Breathing', year: 2019, bpm: 121, key: '3A', energy: 4, genre: 'melodic house' },
    { artist: 'Eric Prydz', title: 'Opus', year: 2015, bpm: 126, key: '9A', energy: 9, genre: 'progressive house' },
    { artist: 'Sasha', title: 'Xpander', year: 1999, bpm: 132, key: '8A', energy: 9, genre: 'progressive house' },
    { artist: 'Black Coffee ft. Bucie', title: 'Superman', year: 2010, bpm: 121, key: '4A', energy: 4, genre: 'afro house' },
    { artist: '&ME', title: 'The Rapture Pt.II', year: 2018, bpm: 120, key: '7A', energy: 5, genre: 'afro house' },
    { artist: 'Culoe De Song', title: 'Webaba', year: 2009, bpm: 122, key: '10A', energy: 5, genre: 'afro house' },
    { artist: 'Fisher', title: 'Losing It', year: 2018, bpm: 125, key: '11A', energy: 10, genre: 'tech house' },
    { artist: 'Green Velvet & Patrick Topping', title: 'Voicemail', year: 2016, bpm: 126, key: '10A', energy: 9, genre: 'tech house' },
    { artist: 'Hot Since 82', title: 'Buggin\' (ft. Jem Cooke)', year: 2019, bpm: 124, key: '8A', energy: 7, genre: 'tech house' },
    { artist: 'Dom Dolla', title: 'San Frandisco', year: 2019, bpm: 126, key: '7A', energy: 9, genre: 'tech house' },
    { artist: 'Chris Lorenzo', title: 'California Dreamin\'', year: 2015, bpm: 126, key: '9A', energy: 9, genre: 'bass house' },
    { artist: 'DJ Boring', title: 'Winona', year: 2016, bpm: 122, key: '9A', energy: 4, genre: 'lo-fi house' },
    { artist: 'Ross From Friends', title: 'Talk To Me You\'ll Understand', year: 2015, bpm: 120, key: '10B', energy: 3, genre: 'lo-fi house' },
    { artist: 'Disclosure ft. Sam Smith', title: 'Latch', year: 2012, bpm: 122, key: '10B', energy: 7, genre: 'uk garage' },
    { artist: 'Peggy Gou', title: 'It Makes You Forget (Itgehane)', year: 2018, bpm: 120, key: '11A', energy: 5, genre: 'deep house' },
    { artist: 'Purple Disco Machine', title: 'Hypnotized', year: 2020, bpm: 122, key: '1A', energy: 6, genre: 'funky house' },
    { artist: 'Danny Tenaglia ft. Celeda', title: 'Music Is the Answer', year: 1998, bpm: 127, key: '10A', energy: 8, genre: 'latin house' },
    { artist: 'Josh Wink', title: 'Higher State of Consciousness', year: 1995, bpm: 128, key: '2A', energy: 9, genre: 'acid house' },
    { artist: 'Sébastien Léger', title: 'Lava', year: 2019, bpm: 120, key: '12A', energy: 4, genre: 'organic house' },
    { artist: 'Loleatta Holloway', title: 'Love Sensation', year: 1980, bpm: 119, key: '5B', energy: 6, genre: 'garage house' },
    { artist: 'CamelPhat & Elderbrook', title: 'Cola', year: 2017, bpm: 122, key: '12A', energy: 7, genre: 'tech house' },
    { artist: 'Honey Dijon ft. Annette Bowen & Nikki-O', title: 'Downtown', year: 2020, bpm: 124, key: '2A', energy: 6, genre: 'chicago house' },
  ],

  // ---- BOOTH WISDOM -----------------------------------------------------------
  tips: [
    'Record every set you play — even bedroom practice. Listening back is the fastest way to hear sloppy phrasing and lazy EQ moves you never notice live.',
    'Mix out of a track before the crowd gets tired of it, not after. Leave them wanting one more bar.',
    'The best transition is the one nobody notices. The second best is the one everybody notices — know which one the moment calls for.',
    'Always carry two USB sticks with identical, freshly-exported libraries. One will fail on the night it matters.',
    'Learn every track\'s intro and outro length. The mix starts in your library, not in the booth.',
    'Watch the dancefloor\'s feet, not their phones. Feet never lie.',
    'Your warm-up set is an audition for the headliner standing behind you. Build the room; don\'t torch it.',
    'When a mix goes wrong, commit — cut, echo out, or slam the fader. A confident trainwreck recovery reads as intentional; a timid one never does.',
    'Gain staging beats loudness. A clean signal at moderate level sounds louder than a clipped one at max.',
    'Practice beatmatching by ear even if you use sync. The day the beatgrid is wrong, your ears are the backup system.',
    'One genre, three eras: mixing a 1986 classic into a 2024 cut of the same lineage tells a story no playlist can.',
    'Talk to the sound engineer before you play. They control 80% of how good you sound.',
    'Keep an "emergency" playlist of five guaranteed floor-fillers for when a risk empties the floor. Everyone needs a parachute.',
    'Key clash matters most in breakdowns, when melodies are exposed. Drum-on-drum sections forgive almost any key.',
    'Don\'t redline the master. Ever. The system won\'t get louder — it will get worse.',
    'Wear earplugs on long nights. Tinnitus is the only thing in DJing that is truly permanent.',
    'Steal transitions from sets you love: find the recording, note the timestamps, reverse-engineer the EQ moves. Every great DJ learned this way.',
    'A B2B set is a conversation, not a competition. Leave your partner somewhere generous to go next.',
    'End your set one energy notch below the absolute peak — the last memory should be euphoric, not exhausted.',
    'Silence is an FX unit. A one-beat full cut before a drop hits harder than any riser.',
  ],
};

window.DJKnowledge = DJ_KNOWLEDGE;
